version: '2'
services:
    weapp-app:
        image: weapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://weapp-mysql:3306/weapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 3030:3030
    weapp-mysql:
        extends:
            file: mysql.yml
            service: weapp-mysql
        ports:
            - 3308:3306
    weapp-nginx:
        image: weapp-nginx
        links:
            - weapp-app:weapp-app
        ports:
            - 3000:3000
